management.endpoints.web.exposure.include=health,prometheus,metrics
management.endpoint.prometheus.access=read-only
management.endpoint.metrics.access=read-only
management.metrics.tags.service=inventory-service
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.metrics.distribution.percentiles-histogram.http.server.requests=true
